# 清单相关接口

@baseUrl = http://localhost:3000/api
@baseTag = list
@baseTag2 = task
@contentType = application/json

### 增加清单【增】【auth】

# @name createList
POST {{baseUrl}}/{{baseTag}} HTTP/1.1
content-type: {{contentType}}

{
    "name": "test",
    "color": "#fff"
}

### 删除清单【删】【auth】

DELETE {{baseUrl}}/{{baseTag}}/{{createList.response.body.$._id}} HTTP/1.1

### 修改清单【改】【auth】

PUT {{baseUrl}}/{{baseTag}}/{{createList.response.body.$._id}} HTTP/1.1
content-type: {{contentType}}

{
    "type": "2"
}

### 查询清单（详情）【查】【auth】

GET {{baseUrl}}/{{baseTag}}/{{createList.response.body.$._id}} HTTP/1.1

### 查询清单（列表）【查】【auth】

GET {{baseUrl}}/{{baseTag}}
    ?page=1
    &pageSize=20

### 增加任务【增】【auth】

# @name createTask
POST {{baseUrl}}/{{baseTag2}}/{{createList.response.body.$._id}} HTTP/1.1
content-type: {{contentType}}

{
    "name": "test"
}

### 删除任务【删】【auth】

DELETE {{baseUrl}}/{{baseTag2}}/{{createList.response.body.$._id}}/{{createTask.response.body.$._id}} HTTP/1.1

### 修改任务【改】【auth】

PUT {{baseUrl}}/{{baseTag2}}/{{createList.response.body.$._id}}/{{createTask.response.body.$._id}} HTTP/1.1
content-type: {{contentType}}

{
    "type": "2"
}

### 查询任务（单个清单）【查】【auth】

GET {{baseUrl}}/{{baseTag2}}/{{createList.response.body.$._id}} HTTP/1.1

### 查询任务（多个清单）【查】【auth】

GET {{baseUrl}}/{{baseTag2}}
    ?page=1
    &pageSize=20
