# 用户相关接口

@baseUrl = http://localhost:3000/api
@baseTag = user
@contentType = application/json

### 增加用户【增】【admin】

# @name createUser
POST {{baseUrl}}/{{baseTag}} HTTP/1.1
content-type: {{contentType}}

{
    "username": "test",
    "password": "test",
    "name": "test"
}

### 删除用户【删】【admin】

DELETE {{baseUrl}}/{{baseTag}}/{{createUser.response.body.$._id}} HTTP/1.1

### 修改用户【改】【admin】【auth】

PUT {{baseUrl}}/{{baseTag}}/{{createUser.response.body.$._id}} HTTP/1.1
content-type: {{contentType}}

{
    "username": "test1",
    "password": "test1",
    "name": "test2"
}

### 查询用户（详情）【查】【admin】

GET {{baseUrl}}/{{baseTag}}/{{createUser.response.body.$._id}} HTTP/1.1

### 查询用户（列表）【查】【admin】

GET {{baseUrl}}/{{baseTag}}
    ?page=1
    &pageSize=20

### 获取当前登入用户

GET {{baseUrl}}/{{baseTag}}/current HTTP/1.1

### 登入

POST {{baseUrl}}/{{baseTag}}/login HTTP/1.1
content-type: {{contentType}}

{
    "username": "test",
    "password": "test"
}

### 退出登入【cookie】

GET {{baseUrl}}/{{baseTag}}/logout HTTP/1.1
